-- =============================================================================
-- Mission 1: Perform Vector Similarity Search
-- =============================================================================
-- Description: Executes a semantic similarity search using the VECTOR_SEARCH function
--              to find products that are semantically similar to the search query.
--              Uses cosine distance metric to measure similarity between vectors.
--
-- Prerequisites:
--   - 04-get-search-vector.sql must be executed first to generate query vector
--   - Product table must have embeddings populated
--   - Vector index (vec_idx) should be created for optimal performance
--
-- Parameters:
--   - @top: Maximum number of results to consider (default: 50)
--   - @min_similarity: Minimum similarity threshold 0-1 (default: 0.75)
--
-- How It Works:
--   1. Retrieves the query vector from dbo.http_response table
--   2. Uses VECTOR_SEARCH to find nearest neighbors in embedding space
--   3. Filters results by minimum similarity threshold
--   4. Returns top 10 most similar products ordered by distance
--
-- Output Columns:
--   - id: Product identifier
--   - product_name: Name of the matching product
--   - description: Product description
--   - category: Product category
--   - distance: Cosine distance (lower = more similar)
--   - similarity: Calculated similarity score (1 - distance)
--
-- Example Results:
--   For "racing car toys for teenagers", expect XBOX games, building kits,
--   remote control cars, and similar products
-- =============================================================================

